name: Sportradar Proto Sync

on:
  workflow_dispatch:
    inputs:
      sports_endpoints:
        description: 'JSON object mapping sports to their API endpoints (e.g., {"football": "https://api-docs.sportradar.us/NFL/NFL_v7.zip", "baseball": "https://api-docs.sportradar.us/mlb/MLB_v7_Schema.zip"})'
        required: true
        type: string
        default: |
                 {
                   "basketball": "https://api-docs.sportradar.us/nba/NBA_v8_schema.zip",
                   "football": "https://api-docs.sportradar.us/NFL/NFL_v7.zip",
                   "baseball": "https://api-docs.sportradar.us/mlb/MLB_v7_Schema.zip"
                 }

env:
  SCHEMA2PROTO_VERSION: 1.97
  PROTOC_VERSION: 29.3
  PROTOC_GEN_ELIXIR_VERSION: 0.11.0

jobs:
  sync_protos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '25.0'
          elixir-version: '1.14.0'

      - name: Install Protoc
        run: |
          PROTOC_ZIP=protoc-${PROTOC_VERSION}-linux-x86_64.zip
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/$PROTOC_ZIP
          sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
          sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
          rm -f $PROTOC_ZIP
          protoc --version

      - name: Install protoc-gen-elixir
        run: |
          mix escript.install hex protobuf ${PROTOC_GEN_ELIXIR_VERSION} --force
          echo "$HOME/.mix/escripts" >> $GITHUB_PATH

      - name: Download and setup schema2proto
        run: |
            # Create a directory to store our tools
            mkdir -p tools
            
            # We're using Maven Central's repository to download the schema2proto library
            # Maven Central is the primary repository for Java dependencies
            MAVEN_URL="https://repo1.maven.org/maven2"
            
            # The full path to our specific version of schema2proto-lib
            SCHEMA2PROTO_PATH="no/entur/schema2proto-lib/1.97/schema2proto-lib-1.97.jar"
            
            echo "Downloading schema2proto-lib version 1.97 from Maven Central"
            
            # Download with retry logic in case of temporary network issues
            for i in {1..3}; do
              if curl -L --fail "$MAVEN_URL/$SCHEMA2PROTO_PATH" -o "tools/schema2proto.jar"; then
                echo "Download successful!"
                break
              else
                echo "Attempt $i failed. Retrying after 5 seconds..."
                sleep 5
              fi
            done
            
            # Verify our download was successful
            if [ ! -f tools/schema2proto.jar ] || [ ! -s tools/schema2proto.jar ]; then
              echo "Error: Failed to download schema2proto-lib"
              exit 1
            fi
            
            echo "schema2proto-lib has been downloaded and verified"
            ls -l tools/schema2proto.jar

      - name: Process Sportradar Endpoints
        run: |
              # Create working directories
              mkdir -p temp/{xsd,proto,elixir}
              
              # Function to extract league and version from URL
              extract_league_version() {
                local url="$1"
                # Extract league (e.g., NFL, NBA, MLB)
                local league=$(echo "$url" | grep -o '[A-Z]\{3\}' | head -1 | tr '[:upper:]' '[:lower:]')
                # Extract version (e.g., v7, v8)
                local version=$(echo "$url" | grep -o 'v[0-9]\+' | tr '[:upper:]' '[:lower:]')
                echo "$league $version"
              }
              
              # Parse endpoints from input JSON and process each sport
              echo '${{ inputs.sports_endpoints }}' | jq -r 'to_entries | .[] | @text "\(.key) \(.value)"' | while read -r sport endpoint; do
                # Extract league and version from the endpoint URL
                read -r league version <<< $(extract_league_version "$endpoint")
                
                echo "Processing $sport/$league $version from $endpoint"
                
                # Create sport-specific directories
                mkdir -p temp/xsd/$sport/$league temp/proto/$sport/$league temp/elixir/$sport/$league
                
                # Download and unzip the schema
                ZIP_FILE="temp/$sport-$league-schema.zip"
                curl -L "$endpoint" -o "$ZIP_FILE"
                unzip -o "$ZIP_FILE" -d "temp/xsd/$sport/$league"
                rm "$ZIP_FILE"
    
                # Remove MacOS system files if they exist
                find temp/xsd/$sport/$league -name "._*" -delete
                find temp/xsd/$sport/$league -name ".DS_Store" -delete
                find temp/xsd/$sport/$league -name "__MACOSX" -type d -exec rm -r {} +
                
                # Convert XSD to Proto
                find "temp/xsd/$sport/$league" -name "*.xsd" -type f | while read -r xsd_file; do
                  echo "Converting $xsd_file to proto"
                  
                  output_dir="temp/proto/$sport/$league"
                  mkdir -p "$output_dir"
                  
                  # Get the directory containing the current XSD file
                  xsd_dir=$(dirname "$xsd_file")
                  
                  java -jar tools/schema2proto.jar \
                    --outputDirectory="$output_dir" \
                    --outputFilename="$(basename "$xsd_file" .xsd).proto" \
                    --defaultProtoPackage="sportradar.sports.$sport.$league.$version" \
                    --options="java_package:com.sportradar.sports.$sport.$league.$version" \
                    --includeMessageDocs=true \
                    --includeFieldDocs=true \
                    --customImportLocations="$xsd_dir" \
                    "$xsd_file"
                  
                  # Generate Elixir code if proto file was created successfully
                  proto_file="$output_dir/$(basename "$xsd_file" .xsd).proto"
                  if [ -f "$proto_file" ]; then
                    echo "Generating Elixir code for $proto_file"
                    
                    # Create output directory structure
                    mkdir -p "lib/sportradar/sports/$sport/$league/$version"
                    
                    protoc \
                      --elixir_out="lib/sportradar/sports/$sport/$league/$version" \
                      --proto_path="$output_dir" \
                      "$proto_file"
                  fi
                done
              done

      - name: Clean up temporary files
        run: |
          rm -rf temp
  
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add lib/sportradar
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update Sportradar proto definitions"
            git push origin main
          fi